### ISSUE TITLE
Can we document the purpose and/or compatability of the main branches?

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.layout#109]
Would be very useful for e.g. my [question](https://github.com/plone/plone.app.layout/pull/108#issue-197053102) on #108

**Comment by mauritsvanrees** [comment]
I always fear if we document this in a readme, that this information will get out of date.
`plone.app.layout` is a core Plone package, so you should always simply use the version that is pinned by Plone.

If you want to develop on this package, best is to look at the various branches of the [coredev buildout](https://github.com/plone/buildout.coredev). The [`sources.cfg`](https://github.com/plone/buildout.coredev/blob/5.1/sources.cfg#L60) file will show you which branch is used on that coredev branch. So currently:
- Plone 5.1: master branch
- Plone 5.0: 2.5.x branch
- Plone 4.3: 2.3.x branch

The question you link to is about compatibility with LinguaPlone and plone.app.multilingual. I don't think it is doable to document that in `plone.app.layout`, because it uses dozens of packages and we would then need to document the compatibility for all of them, which will get out of date even sooner.

If we know that `plone.app.layout` needs at least version X of a certain package, then we can simply add this in the `setup.py`.

**Comment by gforcada** [comment]
@mauritsvanrees maybe we could add a generic:

```
Plone version compatibility:
============================

See pinned versions for:
- 4.3[link to dist.plone.XXX]
- 5.0[link to dist.plone.XXX]
- 5.1[link to dist.plone.XXX]
```

So the only update needed on all packages would be to add/remove new versions as they are supported. Or only point to http://dist.plone.org/release/ and tell them to look inside the version they want the ``versions.cfg``.

**Comment by djowett** [comment]
@mauritsvanrees thanks for your thought through answer.

To clarify though, I'm not asking for a mention of PAM or LinguaPlone here.  But some kind of "contract" or "commitment" in the README helps me in my situation where I need to know how defensively to code & how many combinations to test in my sitemap fixes.  (It might be a rare situation because fixes for an issue PAM need to be made in p.a.layout - but I suspect it's not too infrequent)

What I was thinking about was something similar to https://github.com/plone/plone.app.contenttypes#compatibility, so for here, perhaps the following would be OK?

## Compatibility

   * the 2.2.x series is for use in Plone 4.2 [and anything else??]
   * the 2.3.x series is for use in Plone 4.3
   * the 2.5.x series is for use in Plone 5.0
   * the 2.6.x series (currently master branch) is for use in Plone 5.1

Using other combinations *might* work, but you may find getting support for that harder.

I think that wouldn't require much "maintainance", right?

**Comment by mauritsvanrees** [comment]
Ah, sure, something like that would be fine.  And 2.2.x is indeed for Plone 4.2 only.

For `plone.app.contenttypes` there is a bit more need for compatibility info, because it was not part of the core in Plone 4.3.

BTW, I have a [script](https://gist.github.com/mauritsvanrees/99cb4a25b622479e7dc3) to download all versions files from dist.plone.org. I use `grep` to search through these when I want to know which version of a package was used in which Plone version.
