### ISSUE TITLE
The social viewlet currently doesn't point to the canonical urls

### ISSUE THREAD

**Issue by jladage** [plone/plone.app.layout#118]
While rendering the og-tags and twitter card tags we reuse Products.CMFPlone.browser.syndication.adaptersFolderFeed's dataset. Unfortunately this generates urls that point to the actual object instead of the canonical url of the default page in og:url and twitter:url.

E.g. on the homepage the url /front-page is used, but should be / in my humble opinion.

**Comment by jladage** [comment]
@mauritsvanrees would you be so kind to fix this?

I like reuse, but isn't it strange to reuse something that return a list of everything in a folder, seems like unnecessary data retrieval to me.

I don't know exactly what other component to use, but it needs to be aware of default pages, so my first thought is to reuse the part that creates the canonical url of a context.

**Comment by mauritsvanrees** [comment]
You can ask a feed for a list of items, but there is no code in the social viewlet that actually does that, so that is no problem.

The feed stuff is useful for getting a description, link, and enclosures/files, regardless of whether the context is Archetypes or dexterity. So that is handy.

What remains then, is the url. Currently we get the base url, which is just the absolute url, plus maybe `/view` appended in case of files or images. The canonical url would be better, except when we want to use `/view`. That could be done in the social viewlet, but is probably best done in the feed code in `CMFPlone`. I am working on a pull request there.
