### ISSUE TITLE
new 2.7.x release?

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.layout#147]
I would need that for a fix in p.a.mosaic

@plone/release-team

**Comment by ale-rt** [comment]
I am +1 on https://github.com/plone/buildout.coredev/pull/459 and I would just release 2.8.0.
I would say that the branch 2.7.x can be left there for the future.

**Comment by mauritsvanrees** [comment]
Thanks. I have merged your readme update and my coredev 5.1 branch change, and have released `plone.app.layout 2.8.0`, for use in Plone 5.1 and 5.2. @agitator: enjoy!

**Comment by agitator** [comment]
@mauritsvanrees the 2.8.0 somehow didn't make it into http://dist.plone.org/release/5.1.2/versions.cfg

what was missing? how to fix that?

**Comment by mauritsvanrees** [comment]
Plone 5.1.2 was already pending at that time I think, and development goes on during that stage, and only really needed changes are added to the pending versions, otherwise the pending release is too much of a moving target to test properly. So the plone.app.layout release was too late to be included. (I don't remember the exact timeline of events.)

We really don't change the versions anymore after a final release. So now it is waiting for a 5.1.3 release, and meanwhile update the pin in any projects that need it.

**Comment by agitator** [comment]
ok ;-) 

what's the process to include p.a.* packages into a release? thought there was some kind of automatism?

**Comment by mauritsvanrees** [comment]
Yes there is. They are taken from the `versions.cfg` in the coredev branches. When Eric creates a pending versions file, he basically copies the `versions.cfg` file to `dist.plone.org`. Around release team we make sure the `checkouts.cfg` is almost empty.

It should be just a few days between pending and final, but in this case it took much longer, which makes it seem like the layout pin was somehow forgotten, but that is not the case.
