### ISSUE TITLE
Wrong use of "show excluded items" in navigation control panel

### ISSUE THREAD

**Issue by erral** [plone/plone.app.layout#190]
The new global navigation checks the "show_excluded_items" settings of the Navigation Control Panel, and if the option is unchecked adds "exclude_from_nav=False" to the catalog query to render the main navigation.

This is wrong because the meaning of the "show_excluded_items" option is to *Show items normally excluded from navigation if viewing their children* according to the message that is shown in the control panel.

The exclude_from_nav option should be enforced **always** or change the meaning of the "show_excluded_items" option (and also the default value, because the default is nowadays True)

Here is the control panel definition:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L830

Here is the check in the global menu viewlet:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L316

Comments @ale-rt ?

**Comment by ale-rt** [comment]
I think you are right! I will try to provide a fix in the weekend if none can fix it before

**Comment by petschki** [comment]
@erral @ale-rt @agitator I just wrapped my head around this.

Its not that easy, because if we want to have the intendet behavior of `show_excluded_items` we cannot apply the `exclude_from_nav` index but have to check it while iterating over the navtree items, depending on the context where we are. So right now it's correct to set `exclude_from_nav` only if `show_excluded_items` is False, but the other way round is simply not implemented.

I can implement this, but I'd recommend to change the default setting of `show_excluded_items` to False with a remark, that enabling this can slow down the navigation ... what do you think?

/cc @jensens

**Comment by petschki** [comment]
and this needs to be changed too: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/navigation.py#L151-L153 ... top level tabs are handled there 🤔

**Comment by erral** [comment]
I would say that the intended behaviour of the "show_excluded_items" checkbox can't be fulfilled with the new implementation of the navigation, and I'm fine with it, as said, I have never understood the use-case for that. 

So I would delete that from the navigation controlpanel and remove all of it checks, and enforce everywhere the excluded_from_nav attribute.

**Comment by petschki** [comment]
well, just fiddled around a bit and actually it's not that hard to restore the intendet behavior of `show_excluded_items` in combination with `exclude_from_nav` ... see https://github.com/plone/plone.app.layout/pull/192 ... this also needs https://github.com/plone/Products.CMFPlone/pull/2829 to be merged and released otherwise the toplevel's aren't handled the same way.
